---

#Goal: I have to lint, build and test a Frontend and Backend code, then push the images to Dockerhub

name: CI

on:
  push:
    paths:
      - 'frontend'
      - 'backend'
        #- '**'
        #- '!.github/workflows/**'  # Not include the workflows to build 
    branches: [GA-practice]

jobs:

  # For frontend code we have used node js

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Setup node js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npm 
          cache-dependency-path: frontend/package-lock.json

      - name: install npm packages
        run: npm ci
        working-directory: frontend

      - name: Run linter
        run: npm run lint
        working-directory: frontend

      - name: Run test
        run: npm run test
        working-directory: frontend

  backend:
    runs-on: ubuntu-latest
    steps:

       # For Backend code we have used Go lang

      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Setup Go lang
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Run Go formatter
        # Defines the Go formatting standards
        run: go fmt         
        working-directory: backend

      - name: Run Go vetter
        # Defines the Go compiler issues
        run: go vet
        working-directory: backend

      - name: Run test
        run: go test
        working-directory: backend

  docker-build-push:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['frontend', 'backend']
    steps:
      - name: Code checkout
        uses: actions/checkout@v7

      - name: Docker set up Login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push to docker hub
        uses: docker/build-push-action@v7
        with:
          context: ./${{ matrix.folder }}   # here we are using matrix concept to call and build multiple jobs at a time
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folder }}:latest

  deploy:
    needs: [frontend, backend, docker-build-push]
    uses: ./.github/workflows/cd.yml
    secrets: inherit

  #Above step is used to trigger CD workflow and called in CD.yml workflow    
