---

#Goal: I have to lint, build and test a Frontend and Backend code, then push the images to Dockerhub

name: CI

on:
  push:
    branches: [advanced]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Setup node js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
        cache: npm 
        cache-dependency-path: frontend/package-lock.json

      - name: install npm packages
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run test
        run: npm run test
  #backend:
