#Goal: To run End to End DevSecops Pipeline

name: DevSecOps

on:
  push:
    branches: [DevSecOps]

jobs:
  ## ---- CI -----

  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  dependency-checks:
    uses: ./.github/workflows/dependency-scan.yml

  docker-checks:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit     # To access GITHUB_TOKEN with workflow_call we need to explicitly mention like this to access it

  sonarqube-scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit

  run-tests:
    uses: ./.github/workflows/code-tests.yml

  docker-push:
    uses: ./.github/workflows/docker-push.yml
    needs: [code-quality,run-tests,sonarqube-scan,docker-checks,dependency-checks,secret-scanning]
    secrets: inherit

  ## ---- CD -----

  deploy:
    needs: [docker-push]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
