#Goal: To ensure no Secrets has been leaked in the code

name: Secret-Scanning

on:
  workflow_call:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Gitleeks Scanner
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # By default GITHUB will have some TOKENS if we are checking with gitleaks we need GITHUB_TOKEN
      # Don't share any GITHUB_TOKEN with external PR/MR it might compromise our credentials and falls to wrong person
